version: '3.9'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:kahmada
    container_name: mariadb
    hostname: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - data_vol:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:kahmada
    container_name: wordpress
    hostname: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception_network

  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx:kahmada
    container_name: nginx
    hostname: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception_network

  adminer:
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:80"
    networks:
      - inception_network
    depends_on:
      - mariadb

  static_site:
    build:
      context: ./requirements/bonus/static_site
    container_name: static_site
    restart: always
    ports:
      - "8081:80"
    networks:
      - inception_network
  
  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    restart: always

  ftp:
    build:
      context: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "30000-30100:30000-30100"
    networks:
      - inception_network
    volumes:
      - wordpress_vol:/var/www/html


volumes:
  data_vol:
    driver: local
    driver_opts:
      type: none
      device: /Users/kahmada/Desktop/db
      o: bind
  
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /Users/kahmada/Desktop/wp
      o: bind

networks:
  inception_network:
    name: inception_network
    driver: bridge
