version: '3.5'

volumes:
  wordpress:
    name: v_wp
    driver: local
    driver_opts:
      device: /Users/kahmada/Desktop/inc/Wordpress
      o: bind
      type: none
  mariadb:
    name: v_mariadb
    driver: local
    driver_opts:
      device: /Users/kahmada/Desktop/inc/DB
      o: bind
      type: none
networks:
  inception:
    name: inception
    driver: bridge
services:
  mariadb:
    image: mariadb:42
    container_name: mariadb
    build: ./requirements/mariadb/.
    ports:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress:42
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  nginx:
    image: nginx:42
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception
    restart: always